name: Jessafly Photography
favicon: null
layout_spectrum: 0.26444
typography_spectrum: 0.73559
title: 'Jessafly Photography | Invermere Lifestyle Photographer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#662d91'
    - '#8cd5e3'
    - '#000000'
    - '#6f6f6f'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
