name: Jessafly Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12312
title: Jessafly Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#662d91'
    - '#8cd5e3'
    - '#000000'
    - '#6f6f6f'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.9164768941700459
purpose: []
