name: 'Jessafly | Photography | Art'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73559
title: 'Jessafly | Photography | Art'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#662d91'
    - '#8cd5e3'
    - '#000000'
    - '#6f6f6f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
