layout_spectrum: 0.27245483617298305
typography_spectrum: 0.22150815930217505
color:
  brandColors:
    - '#F7F2B2'
    - '#ADCF4F'
    - '#84815B'
    - '#4A1A2C'
    - '#8E3557'
  brandStrength: 0.2587786866351962
  lightness: 0.8393783292267472
  saturation: 0.9254082085099071
  rhythmicContrast: 0.18895287439227104
name: Jessafly | Photography | Art
favicon: null
title: Jessafly | Photography | Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
